variables:
  - &golang_image 'golang:1.18'
  - &when_path
      # related config files
      - ".woodpecker/build.yml"
      # go source code
      - "**/*.go"

clone:
  git:
    image: woodpeckerci/plugin-git
    when:
      event: 
        - pull_request
        - deployment
        - tag
 
pipeline:
  dependencies:
    image: *golang_image
    group: prepare
    secrets:
      - GITHUB_USERNAME
      - GITHUB_TOKEN
    commands:
      - echo "machine github.com login $${GITHUB_USERNAME} password $${GITHUB_TOKEN}" > /root/.netrc
      - chmod 600 /root/.netrc
      - go env -w GOPRIVATE=github.com/ringsq/*
      - go mod vendor
    when:
      event:
        - pull_request
        - deployment
        - tag

  compile:
    image: *golang_image
    group: build
    commands:
      - env CGO_ENABLED=0 go build -v -ldflags="-X 'main.Version=${CI_COMMIT_TAG:-${CI_COMMIT_SHA:0:6}}'" -o dist/gonetstat main.go
    when:
      event:
        - pull_request
        - deployment
        - tag

  publish:
    image: plugins/github-release
    settings:
      api_key: 
        from_secret: GITHUB_TOKEN
      files: dist/gonetstat
    when:
      event: tag